apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-api
  labels:
    app: rs-api
spec:
  selector:
    matchLabels:
      app: rs-api
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: rs-api
    spec:
      containers:
        - name: rs-api
          image: julianpoy/recipesage:api-$RELEASE_TAG
          ports:
            - containerPort: 3000
          command: ["npx"]
          args:
            [
              "--yes",
              "ts-node",
              "--swc",
              "--project",
              "packages/backend/tsconfig.json",
              "packages/backend/src/bin/www",
            ]
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 300Mi
            limits:
              cpu: 1
              memory: 1G
          envFrom:
            - secretRef:
                name: rs-api-env
          env:
            - name: BROWSERLESS_HOST
              value: "rs-browserless"
            - name: BROWSERLESS_PORT
              value: "3000"
            - name: INGREDIENT_INSTRUCTION_CLASSIFIER_URL
              value: http://rs-ingredient-instruction-classifier:3000/
            - name: SEARCH_PROVIDER
              value: typesense
            - name: STORAGE_TYPE
              value: s3
            - name: INDEX_ON_LOGIN
              value: "true"
            - name: TYPESENSE_NODES
              value: '[{"host": "rs-typesense", "port": 8108, "protocol": "http"}]'
            - name: OPENAI_GPT_MODEL
              value: gpt-3.5-turbo-1106
          volumeMounts:
            - name: firebase-credentials
              mountPath: /app/.credentials/firebase.json
              subPath: firebase-credentials.json
      volumes:
        - name: firebase-credentials
          configMap:
            name: firebase-credentials
      imagePullSecrets:
        - name: myregistrykey
      terminationGracePeriodSeconds: 900
---
apiVersion: v1
kind: Service
metadata:
  name: rs-api
spec:
  type: ClusterIP
  selector:
    app: rs-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rs-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rs-api
  minReplicas: 4
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: 500m
