apiVersion: v1
kind: Secret
metadata:
  name: rs-api-env
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: ""
  AWS_BUCKET: ""
  NODE_ENV: ""
  VERBOSE: ""
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_PORT: ""
  POSTGRES_HOST: ""
  POSTGRES_SSL: ""
  POSTGRES_LOGGING: ""
  GCM_KEYPAIR: ""
  SENTRY_DSN: ""
  GRIP_URL: ""
  GRIP_KEY: ""
  ELASTIC_ENABLE: ""
  ELASTIC_IDX_PREFIX: ""
  ELASTIC_CONN: ""
  ELASTIC_PASSWORD: ""
  STRIPE_SK: ""
  STRIPE_WEBHOOK_SECRET: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: rs-elastic-env
stringData:
  ELASTIC_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: rs-pushpin-env
stringData:
  GRIP_KEY: ""
